import Circle from './shape/Circle'
import Line from './shape/Line'
import AbstractUi from './shape/AbstractUi'
import Rect from './shape/Rect'
import Group from './shape/Group'
import Text from './shape/Text'
import BoxHidden from './shape/BoxHidden'

export type IShape = Group | BoxHidden | Circle | Rect | Line | Text | AbstractUi
export type IShapeType = 'Line' | 'Rect' | 'Circle' | 'Text' | 'Group' | 'BoxHidden' | 'Stage'

export type ICursor =
  | 'url'
  | 'default'
  | 'auto'
  | 'crosshair'
  | 'pointer'
  | 'move'
  | 'e-resize'
  | 'ne-resize'
  | 'nw-resize'
  | 'n-resize'
  | 'se-resize'
  | 'sw-resize'
  | 's-resize'
  | 'w-resize'
  | 'text'
  | 'wait'
  | 'help'
